<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220802095019 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annonce CHANGE ID_ETAT ID_ETAT INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE ID_SOUS_CATEGORIE ID_SOUS_CATEGORIE INT DEFAULT NULL, CHANGE ID_VILLE ID_VILLE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE conversation CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE image CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE reservation CHANGE ID_DISPONIBILITE ID_DISPONIBILITE INT DEFAULT NULL, CHANGE ID_EVALUATION ID_EVALUATION INT DEFAULT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sous_categorie CHANGE ID_CATEGORIE ID_CATEGORIE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur DROP RESET_TOKEN, CHANGE DATE_NAISSANCE DATE_NAISSANCE DATE DEFAULT \'NULL\', CHANGE GENRE GENRE CHAR(1) DEFAULT \'NULL\', CHANGE PHOTO_UTILISATEUR PHOTO_UTILISATEUR VARCHAR(100) DEFAULT \'NULL\', CHANGE MDP_UTILISATEUR MDP_UTILISATEUR VARCHAR(50) NOT NULL, CHANGE MAIL_UTILISATEUR MAIL_UTILISATEUR VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE ville CHANGE ID_DEPARTEMENT ID_DEPARTEMENT INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE annonce CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_SOUS_CATEGORIE ID_SOUS_CATEGORIE INT NOT NULL, CHANGE ID_VILLE ID_VILLE INT NOT NULL, CHANGE ID_ETAT ID_ETAT INT NOT NULL');
        $this->addSql('ALTER TABLE conversation CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE image CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation CHANGE ID_EVALUATION ID_EVALUATION INT NOT NULL, CHANGE ID_DISPONIBILITE ID_DISPONIBILITE INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE sous_categorie CHANGE ID_CATEGORIE ID_CATEGORIE INT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD RESET_TOKEN VARCHAR(50) DEFAULT NULL, CHANGE DATE_NAISSANCE DATE_NAISSANCE DATE DEFAULT NULL, CHANGE GENRE GENRE CHAR(1) DEFAULT NULL, CHANGE PHOTO_UTILISATEUR PHOTO_UTILISATEUR VARCHAR(100) DEFAULT NULL, CHANGE MDP_UTILISATEUR MDP_UTILISATEUR VARCHAR(150) NOT NULL, CHANGE MAIL_UTILISATEUR MAIL_UTILISATEUR VARCHAR(150) NOT NULL');
        $this->addSql('ALTER TABLE ville CHANGE ID_DEPARTEMENT ID_DEPARTEMENT INT NOT NULL');
    }
}
