<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20221005111855 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY region_ibfk_1');
        $this->addSql('DROP TABLE region');
        $this->addSql('ALTER TABLE annonce CHANGE ID_ETAT ID_ETAT INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE ID_SOUS_CATEGORIE ID_SOUS_CATEGORIE INT DEFAULT NULL');
        $this->addSql('CREATE FULLTEXT INDEX IDX_F65593E552747B74CDBD270E ON annonce (TITRE_ANNONCE, DESCRIPTION_ANNONCE)');
        $this->addSql('ALTER TABLE conversation CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE departement DROP FOREIGN KEY departement_ibfk_1');
        $this->addSql('DROP INDEX CODE_DEPARTEMENT ON departement');
        $this->addSql('DROP INDEX CODE_REGION ON departement');
        $this->addSql('ALTER TABLE departement DROP CODE_REGION');
        $this->addSql('ALTER TABLE image CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE reservation CHANGE ID_DISPONIBILITE ID_DISPONIBILITE INT DEFAULT NULL, CHANGE ID_EVALUATION ID_EVALUATION INT DEFAULT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT DEFAULT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT DEFAULT NULL');
        $this->addSql('ALTER TABLE sous_categorie CHANGE ID_CATEGORIE ID_CATEGORIE INT DEFAULT NULL');
        $this->addSql('ALTER TABLE utilisateur CHANGE DATE_NAISSANCE DATE_NAISSANCE DATETIME DEFAULT \'NULL\', CHANGE GENRE GENRE CHAR(1) DEFAULT \'NULL\', CHANGE PHOTO_UTILISATEUR PHOTO_UTILISATEUR VARCHAR(100) DEFAULT \'NULL\', CHANGE MDP_UTILISATEUR MDP_UTILISATEUR VARCHAR(50) NOT NULL, CHANGE MAIL_UTILISATEUR MAIL_UTILISATEUR VARCHAR(50) NOT NULL, CHANGE IP_INSCRIPTION ip_inscription VARCHAR(50) NOT NULL, CHANGE ROLE_UTILISATEUR ROLE_UTILISATEUR VARCHAR(50) NOT NULL, CHANGE RESET_TOKEN RESET_TOKEN VARCHAR(50) NOT NULL, CHANGE IS_VERIFIED IS_VERIFIED TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE ville CHANGE CODE_POSTAL CODE_POSTAL CHAR(5) NOT NULL, CHANGE CODE_INSEE CODE_INSEE CHAR(5) NOT NULL, CHANGE LATITUDE LATITUDE NUMERIC(10, 0) NOT NULL, CHANGE LONGITUDE LONGITUDE NUMERIC(10, 0) NOT NULL, CHANGE ID_DEPARTEMENT ID_DEPARTEMENT INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ville ADD CONSTRAINT FK_43C3D9C32A7D3751 FOREIGN KEY (ID_DEPARTEMENT) REFERENCES departement (ID_DEPARTEMENT)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE region (ID_REGION INT NOT NULL, CODE_REGION INT NOT NULL, NOM_REGION VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, SLUG_REGION VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, UNIQUE INDEX CODE_REGION (CODE_REGION), PRIMARY KEY(ID_REGION)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT region_ibfk_1 FOREIGN KEY (ID_REGION) REFERENCES departement (ID_DEPARTEMENT) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX IDX_F65593E552747B74CDBD270E ON annonce');
        $this->addSql('ALTER TABLE annonce CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_SOUS_CATEGORIE ID_SOUS_CATEGORIE INT NOT NULL, CHANGE ID_ETAT ID_ETAT INT NOT NULL');
        $this->addSql('ALTER TABLE conversation CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE departement ADD CODE_REGION INT NOT NULL');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT departement_ibfk_1 FOREIGN KEY (ID_DEPARTEMENT) REFERENCES ville (ID_VILLE) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX CODE_DEPARTEMENT ON departement (CODE_DEPARTEMENT)');
        $this->addSql('CREATE INDEX CODE_REGION ON departement (CODE_REGION)');
        $this->addSql('ALTER TABLE image CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE messenger_messages CHANGE delivered_at delivered_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE reservation CHANGE ID_EVALUATION ID_EVALUATION INT NOT NULL, CHANGE ID_DISPONIBILITE ID_DISPONIBILITE INT NOT NULL, CHANGE ID_UTILISATEUR ID_UTILISATEUR INT NOT NULL, CHANGE ID_ANNONCE ID_ANNONCE INT NOT NULL');
        $this->addSql('ALTER TABLE sous_categorie CHANGE ID_CATEGORIE ID_CATEGORIE INT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur CHANGE DATE_NAISSANCE DATE_NAISSANCE DATE DEFAULT NULL, CHANGE GENRE GENRE CHAR(1) DEFAULT NULL, CHANGE PHOTO_UTILISATEUR PHOTO_UTILISATEUR VARCHAR(100) DEFAULT NULL, CHANGE MDP_UTILISATEUR MDP_UTILISATEUR VARCHAR(250) NOT NULL, CHANGE MAIL_UTILISATEUR MAIL_UTILISATEUR VARCHAR(250) NOT NULL, CHANGE ip_inscription IP_INSCRIPTION VARCHAR(15) NOT NULL, CHANGE ROLE_UTILISATEUR ROLE_UTILISATEUR VARCHAR(100) NOT NULL, CHANGE RESET_TOKEN RESET_TOKEN VARCHAR(50) DEFAULT NULL, CHANGE IS_VERIFIED IS_VERIFIED VARCHAR(1) NOT NULL');
        $this->addSql('ALTER TABLE ville DROP FOREIGN KEY FK_43C3D9C32A7D3751');
        $this->addSql('ALTER TABLE ville CHANGE CODE_POSTAL CODE_POSTAL VARCHAR(5) DEFAULT NULL, CHANGE CODE_INSEE CODE_INSEE VARCHAR(5) DEFAULT NULL, CHANGE LATITUDE LATITUDE DOUBLE PRECISION NOT NULL, CHANGE LONGITUDE LONGITUDE DOUBLE PRECISION NOT NULL, CHANGE ID_DEPARTEMENT ID_DEPARTEMENT INT NOT NULL');
    }
}
